# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('wantedinr', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
