# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inr',
            name='testdate',
            field=models.DateTimeField(),
        ),
    ]
