# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0004_auto_20170724_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useddrugs',
            name='userlogin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrtracker.User'),
        ),
    ]
