# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0005_auto_20170724_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='testtype',
            field=models.CharField(max_length=200),
        ),
    ]
