# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0006_auto_20170726_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nexttestdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
