# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0007_test_nexttestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 7, 26, 7, 57, 13, 461882, tzinfo=utc)),
        ),
    ]
