# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0008_auto_20170726_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_dose', models.CharField(max_length=40)),
                ('date_prediction', models.DateTimeField()),
                ('INR_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrtracker.INR')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(),
        ),
    ]
