# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0010_auto_20170727_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='predicted_data_test',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 7, 27, 8, 24, 40, 545040, tzinfo=utc)),
        ),
    ]
