# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0011_auto_20170727_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='prediction_message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 7, 27, 8, 41, 43, 912355, tzinfo=utc)),
        ),
    ]
