# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0012_auto_20170727_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 7, 27, 15, 0, 36, 574125, tzinfo=utc)),
        ),
    ]
