# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0013_auto_20170727_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='useddrugs',
            name='smalest_part',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 8, 4, 22, 36, 6, 565896, tzinfo=utc)),
        ),
    ]
