# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0014_auto_20170805_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useddrugs',
            old_name='smalest_part',
            new_name='smallest_part',
        ),
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 8, 4, 22, 36, 39, 236631, tzinfo=utc)),
        ),
    ]
