# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-06 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inrtracker', '0015_auto_20170805_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='hour',
            field=models.TimeField(default=datetime.datetime(2017, 8, 6, 18, 8, 41, 455997, tzinfo=utc)),
        ),
    ]
